# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='autor', max_length=50),
        ),
    ]
